# entrypoint: "gunicorn -b :8080 main:app"
# env: flex
# runtime: python
# runtime_config:
#   python_version: 3.9.7
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 4
# resources:
#   memory_gb: 6